### ISSUE TITLE
After updating to 2.0.12 I get lorawan.cpp error: 'lmh_reset_mac' was not declared in this scope

### ISSUE THREAD

**Issue by AndreasESchneider** [beegee-tokyo/WisBlock-API-V2#1]
First of all many thanks for this great library.

After updating to 2.0.12 I get a 'lmh_reset_mac was not declared in this scope' error message (IDE VS Code with Platformio). 

I see the call in lorawan.cpp but I don't know if this is a function which I have to implement myself and what this function should do. Can you please throw me a hint regarding this error message, many thanks.

**Comment by beegee-tokyo** [comment]
Roll back to V2.0.11.

Something went wrong.

**Comment by beegee-tokyo** [comment]
Are you using PIO or Arduino IDE?

I am not getting any errors on PIO

**Comment by beegee-tokyo** [comment]
Or try to clean the project.
I am not getting any error.

**Comment by AndreasESchneider** [comment]
Thank you for your super fast feedback. I am using VSC and PIO on a Windows 10 (Intel). All versions are up-to-date.

As recomended I fully cleaned the project but got the same error message during the build. However PIO did not update to the latest SX126x-Arduino package (was still on ^2.0.19, don't know why). If I am setting the version to ^2.0.20 in platformio.ini I get the following error:

"UnknownPackageError: Could not find the package with 'beegee-tokyo/SX126x-Arduino @ ^2.0.20' requirements for your system 'windows_amd64"'

Maybe 2.0.20 is not in the reach of PIO right now, I will way a couple of days and retryl later.

In any case, many thanks for your help. Very appreciated.

**Comment by beegee-tokyo** [comment]
Strange, I updated both at the same time. And I checked, the SX126x-Arduino library is on 2.0.20 after I did pio package update

**Comment by AndreasESchneider** [comment]
Only fyI: deleting the PIO .cache folder under C:\Users\[username]\.platformio did the job.

**Comment by beegee-tokyo** [comment]
Interesting, never had to clear that one.
But good to know.
Thanks for sharing.
